name: Airflow CI/CD Pipeline
on:
  pull_request:
    branches:
      - master
    paths:
      - 'airflow/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - run: tree
      - name: Airflow DAGs Validation
        uses: jayamanikharyono/airflow-dag-action@master
        with:
          requirementsFile: airflow/requirements.txt
          dagPaths: airflow/dags
          varFile: airflow/variables.json
          accessToken: ${{ secrets.GITHUB_TOKEN }}
