name: Main CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls
      - run: pwd
      - name: Render Python Project
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          datafile: template_data.json
          path: /*
      - name: Sync To GCS
        uses: ./action/action-gcloud
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: rsync -d -r main.py gs://github_action_test
          cli: gsutil
