name: Main CI/CD Pipeline
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get diff files
        id: diff_files
        run: |
          echo "::set-output name=addmodified::$(git diff --name-only --no-merges master) | tr ' ' ','"
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.diff_files.outputs.addmodified }}"
      - run: ls
      - run: pwd
      - name: Render Python Project
        uses: jayamanikharyono/jinja-action@v0.1
        with:
          datafile: template_data.json
          path: ./*.py
      - name: Airflow DAGs Validation
        uses: jayamanikharyono/airflow-dag-action@v0.1-alpha
        with:
          requirementsFile: airflow/requirements.txt
          dagPaths: airflow/dags
          varFile: airflow/var_stg.json
      - name: Sync To GCS
        uses: ./action/action-gcloud
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        with:
          args: rsync -d -r $PWD gs://github_action_test
          cli: gsutil
